### ISSUE TITLE
Misaligned header pins / daisy patch library footprint / kivu12.kicad_pcb

### ISSUE THREAD

**Issue by da6353** [ohmtech-rdi/eurorack-blocks#455]
Header pins in library footprint (DaisyPatchSM) for daisy patch are slightly misaligned, see attached screen shots for comparison.

![ES_Daisy_Patch_SM_front](https://user-images.githubusercontent.com/58539521/180666077-a991dd97-08c3-42e4-8bf9-c83682fb9c21.png)
![render-3d](https://user-images.githubusercontent.com/58539521/180666078-8740ada0-bc8d-43fe-be73-e81ae858a785.png)
![DaisyPatchSm](https://user-images.githubusercontent.com/58539521/180666202-9c4f76c5-7f95-4c66-bea1-9f20deaed53b.png)

**Comment by ohmtech-rdi** [comment]
Hi @da6353 !

If you refer to the plated through-holes zig-zag pattern, that actually comes from the Electro-smith Eagle layout, and was just converted this way in Kicad.

Electro-smith did that actually on purpose: If you use headers with squared pins, this will slightly tighten the header in place when hand-soldering. Having used that we find it pretty smart! And so the power connector is not done this way, so we are thinking of making the same thing for it.

@da6353 Do you have any trouble with that zigzag pattern when soldering?

Please keep us posted, thanks!

**Comment by da6353** [comment]
Thanks!

I make a generic matching 12HP front user panel protoboard, and also a 14HP
version ('kivu14'), which has pin headers realigned, so that standard pcb
protoboard can be used, for the front user panel.

Thanks, Don

[image: image.png]

[image: image.png]

**Comment by ohmtech-rdi** [comment]
Hi @da6353 

> I make a generic matching 12HP front user panel protoboard, and also a 14HP
version ('kivu14'), which has pin headers realigned, so that standard pcb
protoboard can be used, for the front user panel.

Ah I see! But the pin headers that have this zigzag pattern are meant for the Daisy Patch Submodule, and are going to the back of the `kivu12` board, right.

Having a protoboard for the front user panel is indeed a smart idea!

As for names, the idea was to use lakes in Africa, suffixed with the HP size.

Thanks!
